export const INDIAN_CITIES = [
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur",
  "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara",
  "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi",
  "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad", "Prayagraj", "Howrah", "Ranchi", "Gwalior",
  "Jabalpur", "Coimbatore", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Guwahati", "Chandigarh", "Solapur",
  "Hubli-Dharwad", "Bareilly", "Moradabad", "Mysore", "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", "Bhubaneswar", "Salem",
  "Mira-Bhayandar", "Warangal", "Guntur", "Bhiwandi", "Saharanpur", "Gorakhpur", "Bikaner", "Amravati", "Noida", "Jamshedpur",
  "Bhilai", "Cuttack", "Firozabad", "Kochi", "Nellore", "Bhavnagar", "Dehradun", "Durgapur", "Asansol", "Rourkela",
  "Nanded", "Kolhapur", "Ajmer", "Akola", "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi",
  "Ulhasnagar", "Nellore", "Jammu", "Sangli-Miraj & Kupwad", "Belgaum", "Mangalore", "Ambattur", "Tirunelveli", "Malegaon", "Gaya",
  "Jalgaon", "Udaipur", "Maheshtala", "Davanagere", "Kozhikode", "Akurn", "Kurnool", "Rajpur Sonarpur", "Rajahmundry", "Bokaro",
  "South Dumdum", "Bellary", "Patiala", "Gopalpur", "Agartala", "Bhagalpur", "Muzaffarnagar", "Bhatpara", "Panihati", "Latur",
  "Dhule", "Rohtak", "Korba", "Bhilwara", "Brahmapur", "Muzaffarpur", "Ahmednagar", "Mathura", "Kollam", "Avadi",
  "Rajahmundry", "Kadapa", "Kamarhati", "Bilaspur", "Shahjahanpur", "Bijapur", "Rampur", "Shimoga", "Chandrapur", "Junagadh",
  "Thrissur", "Alwar", "Bardhaman", "Kulti", "Kakinada", "Nizamabad", "Parbhani", "Tumkur", "Khammam", "Uzhavarkarai",
  "Bihar Sharif", "Panipat", "Darbhanga", "Bally", "Aizawl", "Dewas", "Ichalkaranji", "Karnal", "Bathinda", "Jalna",
  "Eluru", "Barasat", "Kirari Suleman Nagar", "Purnia", "Satna", "Mau", "Sonipat", "Farrukhabad", "Sagar", "Rourkela",
  "Durg", "Imphal", "Ratlam", "Hapur", "Arrah", "Anantapur", "Karimnagar", "Etawah", "Ambernath", "Bharatpur",
  "Begusarai", "New Delhi", "Gandhidham", "Baranagar", "Tiruppur", "Puducherry", "Sikar", "Thoothukudi", "Rewa", "Mirzapur",
  "Raichur", "Pali", "Ramagundam", "Silchar", "Haridwar", "Vijayanagaram", "Tenali", "Nagercoil", "Sri Ganganagar", "Karur",
  "Haldwani-cum-Kathgodam", "Yamunanagar", "Vizianagaram", "Thanjavur", "Arrah", "Hospet", "Mango", "Thane", "Bulandshahr", "Kalyan",
  "Katra", "Gulmarg", "Pahalgam", "Rishikesh", "Kasol", "Munnar", "Ooty", "Kodaikanal", "Dharamshala", "Dalhousie", "Khajuraho",
  "Hampi", "Gokarna", "Jaisalmer", "Pushkar", "Mount Abu", "Alappuzha", "Varkala", "Kumarakom", "Wayanad", "Vagamon",
  "Cherrapunji", "Shillong", "Tawang", "Gangtok", "Pelling", "Ziro", "Majuli", "Kohima", "Kaziranga", "Imphal"
];
